[project]
name = "colbert-server"
version = "0.2.1"
description = "Run ColBERT Wikipedia server"
readme = "README.md"
authors = [
    { name = "Niels van Galen Last", email = "nvangalenlast@gmail.com" }
]
license = "MIT"
keywords = ["colbert", "retrieval", "search", "wikipedia", "ir"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
]
requires-python = ">=3.13"
dependencies = [
    "colbert-ai>=0.2.22",
    "faiss-cpu>=1.12.0",
    "flask>=3.1.2",
    "huggingface-hub>=0.36.0",
    "packaging>=24.1",
    "torch>=2.9.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "isort>=7.0.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.14.2",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
packages = ["torch", "torchvision", "torchaudio", "torchtext"]
explicit = true

[project.scripts]
colbert-server = "colbert_server:main"

[project.urls]
Homepage = "https://github.com/nielsgl/colbert-server"
Repository = "https://github.com/nielsgl/colbert-server"
Issues = "https://github.com/nielsgl/colbert-server/issues"
Dataset = "https://huggingface.co/datasets/nielsgl/colbert-wiki2017"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "colbert_server"
module-root = ""

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["W505"]

[tool.ruff.lint.isort]
force-sort-within-sections = true
