name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      repository:
        description: "Publish target"
        required: true
        default: "pypi"
        type: choice
        options:
          - pypi
          - testpypi

jobs:
  determine-target:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.set-target.outputs.repository }}
    steps:
      - id: set-target
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "repository=${{ github.event.inputs.repository }}" >> "$GITHUB_OUTPUT"
          else
            echo "repository=pypi" >> "$GITHUB_OUTPUT"
          fi

  build:
    runs-on: ubuntu-latest
    needs: determine-target
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.13"

      - name: Build distributions
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [determine-target, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish to ${{ needs.determine-target.outputs.repository }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ needs.determine-target.outputs.repository == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
          password: ${{ needs.determine-target.outputs.repository == 'testpypi' && secrets.TEST_PYPI_API_TOKEN || secrets.PYPI_API_TOKEN }}
          packages-dir: dist
          verify-metadata: true
