name: Verify Release

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  verify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install released package
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir colbert-server

      - name: Smoke tests
        run: |
          colbert-server --version
          colbert-server doctor
        env:
          COLBERT_SERVER_DISABLE_UPDATE_CHECK: "1"
